dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - Pillow
    - PyMySQL
    - certifi
    - cffi
    - cycler
    - jieba
    - joblib
    - kiwisolver
    - pycparser
    - pyparsing
    - python-dateutil
    - pytz
    - scipy
    - tensorflow
    - keras
    - gensim
    - nltk
