dependencies:
  - python=3
  - pip:
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - jieba
    - scipy
    - tensorflow
    - keras
    - gensim
    - nltk
